#!/usr/bin/env bash
# configuring the domain

domain() {
    line=$(dig "$1" "$2" | grep -A1 "ANSWER SECTION:" | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$1 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]; then
    domain "www" "$1"
    domain "lib-01" "$1"
    domain "web-01" "$1"
    domain "web-02" "$1"
elif [ "$#" == 2 ]; then
    domain "$2" "$1"
fi
