#!/usr/bin/env bash
# install nginx web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' >/var/www/html/index.nginx-debian.html
CONFIG="
server {
    listen 80 default_server;
	listen [::]:80 default_server;
    root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
		try_files \$uri \$uri/ =404;
	}
    if ( \$request_filename ~ redirect_me ) {
        rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
}
"

echo -e "$CONFIG" >/etc/nginx/sites-enabled/default

service nginx restart
