#!/usr/bin/env bash
# install nginx web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" >/var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" >/var/www/html/404.html
CONFIG="server {
    listen 80 default_server;
	listen [::]:80 default_server;
    root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
    server_name _;
    location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
    error_page 404 /404.html;
    location = /404.html {
		internal;
	}
}"

echo -e "$CONFIG" >/etc/nginx/sites-enabled/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf

service nginx restart
service nginx start
