#!/usr/bin/env bash
# Display number in list format

for a in $(seq 100); do
	if ((a % 3 == 0 && a % 5 == 0)); then
		echo "FizzBuzz"
	elif ((a % 3 == 0)); then
		echo "Fizz"
	elif ((a % 5 == 0)); then
		echo "Buzz"
	else
		echo "$a"
	fi
done
