#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
a=1
while [ "$a" -le "10" ]; do

	if [ "$a" == "9" ]; then
		echo "Hi"
		a=$((a + 1))
		continue
	fi
	echo "Best School"
	a=$((a + 1))
done
