#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
a=0
while [ "$a" -le "10" ]; do
	if [ "$a" == "9" ]; then
		echo "Hi"
	fi
	if [ "$a" != "9" ]; then
		echo "Best School"
	fi
	a=$((a + 1))
done
