#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
a=0
b=1
while [ "$a" -le "12" ]; do
	echo "Hour: $a"
	b=1
	while [ "$b" -le "59" ]; do
		echo $b
		b=$((b + 1))
	done
	a=$((a + 1))
done
